/**
 * ===============================================================================
 * EXCIPIENT KNOWLEDGE BASE — Фармацевтик ёрдамчи моддалар билимлар базаси
 * ===============================================================================
 * 
 * Ҳар бир ёрдамчи моддалар учун илмий маълумотлар:
 * - Физик-кимёвий хоссалар (молекуляр масса, эришлик, зичлик)
 * - Функционал хусусиятлар (сиқилувчанлик, оқувчанлик)
 * - Фармацевтик мақом (FDA/GRAS)
 * - Оптимал миқдор диапазонлари
 * - Ципрофлоксацин билан мослик
 * 
 * Манбалар: USP-NF, Handbook of Pharmaceutical Excipients (Rowe et al.),
 * FDA Inactive Ingredient Database, PhEur
 * ===============================================================================
 */

const EXCIPIENT_CATEGORIES = {
    FILLER: { name: 'Тўлдирувчи (Filler/Diluent)', nameEn: 'Filler/Diluent', icon: '📦' },
    BINDER: { name: 'Боғловчи (Binder)', nameEn: 'Binder', icon: '🔗' },
    DISINTEGRANT: { name: 'Парчаловчи (Disintegrant)', nameEn: 'Disintegrant', icon: '💥' },
    SUPERDISINTEGRANT: { name: 'Суперпарчаловчи (Superdisintegrant)', nameEn: 'Superdisintegrant', icon: '⚡' },
    LUBRICANT: { name: 'Мойловчи (Lubricant)', nameEn: 'Lubricant', icon: '🧴' },
    GLIDANT: { name: 'Сирғанувчи (Glidant)', nameEn: 'Glidant', icon: '✨' },
    COATING: { name: 'Қобиқ (Film Coating)', nameEn: 'Film Coating Agent', icon: '🛡️' },
    PLASTICIZER: { name: 'Пластификатор (Plasticizer)', nameEn: 'Plasticizer', icon: '🔄' },
    OPACIFIER: { name: 'Матлаштирувчи (Opacifier)', nameEn: 'Opacifier', icon: '⬜' },
    COLORANT: { name: 'Рангловчи (Colorant)', nameEn: 'Colorant', icon: '🎨' },
    SWEETENER: { name: 'Ширинлаштирувчи (Sweetener)', nameEn: 'Sweetener', icon: '🍬' },
    SURFACTANT: { name: 'Сирт-фаол модда (Surfactant)', nameEn: 'Surfactant', icon: '🫧' },
    ANTIOXIDANT: { name: 'Антиоксидант (Antioxidant)', nameEn: 'Antioxidant', icon: '🛡️' }
};

/**
 * Асосий ёрдамчи моддалар базаси
 * Ҳар бир модда учун илмий асосланган маълумотлар
 */
const EXCIPIENTS_DB = {

    // ==================== ТЎЛДИРУВЧИЛАР ====================

    'MCC_PH101': {
        id: 'MCC_PH101',
        name: 'Microcrystalline Cellulose PH-101',
        nameRu: 'Микрокристаллическая целлюлоза PH-101',
        nameUz: 'Микрокристалл целлюлоза PH-101',
        tradeName: 'Avicel PH-101',
        casNumber: '9004-34-6',
        categories: ['FILLER', 'BINDER'],
        molecularWeight: null, // Полимер — аниқ масса йўқ
        empiricalFormula: '(C6H10O5)n',
        solubility: { water: 'Практик эримайди', ethanol: 'Эримайди', acetone: 'Эримайди' },
        solubilityValue: 0, // мг/мл сувда
        density: { bulk: 0.32, tapped: 0.45, true: 1.512 },
        particleSize: { mean: 50, range: [20, 100] }, // мкм
        moistureContent: { max: 5.0, typical: 3.5 }, // %
        compressibility: 0.85, // 0–1 шкалада (юқори = яхши)
        flowability: 0.65, // 0–1 шкалада
        carrIndex: 28, // % (юқори = ёмон оқувчанлик)
        hausnerRatio: 1.39,
        hygroscopicity: 'Паст', // паст/ўрта/юқори
        pH: { range: [5.0, 7.5], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.95, // 0–1 (1 = тўлиқ мос)
        stabilityContribution: 0.85, // барқарорликка ҳиссаси
        dissolutionEffect: 0.70, // эришга таъсири (1 = тезлаштиради)
        disintegrationEffect: 0.60, // парчаланишга таъсири
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 5, max: 40, unit: '%' },
        description: 'Мукаммал сиқилувчанлик, тўлдирувчи ва қуруқ боғловчи сифатида ишлатилади. Тўғридан-тўғри сиқиш усулида муҳим.'
    },

    'MCC_PH102': {
        id: 'MCC_PH102',
        name: 'Microcrystalline Cellulose PH-102',
        nameRu: 'Микрокристаллическая целлюлоза PH-102',
        nameUz: 'Микрокристалл целлюлоза PH-102',
        tradeName: 'Avicel PH-102',
        casNumber: '9004-34-6',
        categories: ['FILLER', 'BINDER'],
        molecularWeight: null,
        empiricalFormula: '(C6H10O5)n',
        solubility: { water: 'Практик эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.30, tapped: 0.43, true: 1.512 },
        particleSize: { mean: 100, range: [50, 200] },
        moistureContent: { max: 5.0, typical: 3.5 },
        compressibility: 0.82,
        flowability: 0.75,
        carrIndex: 22,
        hausnerRatio: 1.28,
        hygroscopicity: 'Паст',
        pH: { range: [5.0, 7.5], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.95,
        stabilityContribution: 0.85,
        dissolutionEffect: 0.70,
        disintegrationEffect: 0.65,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 5, max: 40, unit: '%' },
        description: 'PH-101 га ўхшаш, лекин катта заррача ўлчами яхшироқ оқувчанлик беради.'
    },

    'LACTOSE_MONO': {
        id: 'LACTOSE_MONO',
        name: 'Lactose Monohydrate',
        nameRu: 'Лактоза моногидрат',
        nameUz: 'Лактоза моногидрат',
        tradeName: 'FastFlo 316 / FlowLac 100',
        casNumber: '64044-51-5',
        categories: ['FILLER'],
        molecularWeight: 360.31,
        empiricalFormula: 'C12H22O11·H2O',
        solubility: { water: '210 мг/мл (25°C)', ethanol: 'Эримайди' },
        solubilityValue: 210,
        density: { bulk: 0.55, tapped: 0.75, true: 1.540 },
        particleSize: { mean: 100, range: [50, 200] },
        moistureContent: { max: 5.0, typical: 4.8 },
        compressibility: 0.65,
        flowability: 0.80,
        carrIndex: 18,
        hausnerRatio: 1.22,
        hygroscopicity: 'Паст',
        pH: { range: [4.0, 6.5], typical: 5.0 },
        compatibilityWithCiprofloxacin: 0.80,
        stabilityContribution: 0.75,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 5, max: 50, unit: '%' },
        description: 'Кенг тарқалган тўлдирувчи, сувда яхши эрийди, таблеткага ижобий сиқилувчанлик беради.'
    },

    'CALCIUM_PHOSPHATE': {
        id: 'CALCIUM_PHOSPHATE',
        name: 'Dibasic Calcium Phosphate Dihydrate',
        nameRu: 'Кальций фосфат двузамещенный дигидрат',
        nameUz: 'Кальций фосфат дигидрат',
        tradeName: 'Emcompress / DI-TAB',
        casNumber: '7789-77-7',
        categories: ['FILLER'],
        molecularWeight: 172.09,
        empiricalFormula: 'CaHPO4·2H2O',
        solubility: { water: '0.3 мг/мл', ethanol: 'Эримайди' },
        solubilityValue: 0.3,
        density: { bulk: 0.70, tapped: 0.95, true: 2.389 },
        particleSize: { mean: 150, range: [50, 300] },
        moistureContent: { max: 0.5, typical: 0.2 },
        compressibility: 0.55,
        flowability: 0.85,
        carrIndex: 15,
        hausnerRatio: 1.18,
        hygroscopicity: 'Жуда паст',
        pH: { range: [6.5, 7.5], typical: 7.0 },
        compatibilityWithCiprofloxacin: 0.70,
        stabilityContribution: 0.80,
        dissolutionEffect: 0.45,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 5, max: 45, unit: '%' },
        description: 'Ноорганик тўлдирувчи, яхши оқувчанлик ва барқарорлик, лекин сиқилувчанлик ўрта.'
    },

    // ==================== КРАХМАЛЛАР ====================

    'CORN_STARCH': {
        id: 'CORN_STARCH',
        name: 'Corn Starch (Maize Starch)',
        nameRu: 'Крахмал кукурузный',
        nameUz: 'Маккажўхори крахмали',
        tradeName: 'Starch 1500',
        casNumber: '9005-25-8',
        categories: ['FILLER', 'DISINTEGRANT', 'BINDER'],
        molecularWeight: null,
        empiricalFormula: '(C6H10O5)n',
        solubility: { water: 'Практик эримайди (совуқ сувда)', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.55, tapped: 0.75, true: 1.500 },
        particleSize: { mean: 15, range: [5, 25] },
        moistureContent: { max: 14.0, typical: 11.0 },
        compressibility: 0.45,
        flowability: 0.50,
        carrIndex: 30,
        hausnerRatio: 1.43,
        hygroscopicity: 'Ўрта',
        pH: { range: [4.5, 7.0], typical: 5.5 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.75,
        dissolutionEffect: 0.60,
        disintegrationEffect: 0.65,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 3, max: 15, unit: '%' },
        description: 'Анъанавий боғловчи ва парчаловчи. Оқувчанлик ва сиқилувчанлик ўрта.'
    },

    'PREGELATINIZED_STARCH': {
        id: 'PREGELATINIZED_STARCH',
        name: 'Pregelatinized Starch',
        nameRu: 'Крахмал прежелатинизированный',
        nameUz: 'Прежелатинланган крахмал',
        tradeName: 'Starch 1500 / Lycatab',
        casNumber: '9005-25-8',
        categories: ['FILLER', 'BINDER', 'DISINTEGRANT'],
        molecularWeight: null,
        empiricalFormula: '(C6H10O5)n',
        solubility: { water: 'Қисман эрийди', ethanol: 'Эримайди' },
        solubilityValue: 50,
        density: { bulk: 0.58, tapped: 0.73, true: 1.500 },
        particleSize: { mean: 90, range: [50, 200] },
        moistureContent: { max: 14.0, typical: 10.0 },
        compressibility: 0.65,
        flowability: 0.70,
        carrIndex: 22,
        hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [4.5, 7.0], typical: 5.5 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.78,
        dissolutionEffect: 0.65,
        disintegrationEffect: 0.70,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 5, max: 20, unit: '%' },
        description: 'Оддий крахмалдан яхшироқ сиқилувчанлик ва оқувчанлик. Боғловчи ва парчаловчи сифатида.'
    },

    // ==================== СУПЕРПАРЧАЛОВЧИЛАР ====================

    'CROSPOVIDONE': {
        id: 'CROSPOVIDONE',
        name: 'Crospovidone',
        nameRu: 'Кросповидон',
        nameUz: 'Кросповидон',
        tradeName: 'Polyplasdone XL / Kollidon CL',
        casNumber: '9003-39-8',
        categories: ['SUPERDISINTEGRANT'],
        molecularWeight: null, // Cross-linked polymer
        empiricalFormula: '(C6H9NO)n',
        solubility: { water: 'Практик эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.32, tapped: 0.48, true: 1.220 },
        particleSize: { mean: 40, range: [20, 90] },
        moistureContent: { max: 5.0, typical: 3.0 },
        compressibility: 0.30,
        flowability: 0.60,
        carrIndex: 25,
        hausnerRatio: 1.33,
        hygroscopicity: 'Ўрта',
        pH: { range: [3.0, 7.0], typical: 5.0 },
        compatibilityWithCiprofloxacin: 0.92,
        stabilityContribution: 0.80,
        dissolutionEffect: 0.88,
        disintegrationEffect: 0.95,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 5, unit: '%' },
        description: 'Суперпарчаловчи — капилляр ва шишиш механизми. Жуда тез парчалайди (wicking + swelling).'
    },

    'CROSCARMELLOSE_NA': {
        id: 'CROSCARMELLOSE_NA',
        name: 'Croscarmellose Sodium',
        nameRu: 'Кроскармеллоза натрия',
        nameUz: 'Кроскармеллоза натрий',
        tradeName: 'Ac-Di-Sol / Primellose',
        casNumber: '74811-65-7',
        categories: ['SUPERDISINTEGRANT'],
        molecularWeight: null,
        empiricalFormula: 'Cross-linked CMC-Na',
        solubility: { water: 'Шишийди, эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.38, tapped: 0.58, true: 1.543 },
        particleSize: { mean: 45, range: [20, 100] },
        moistureContent: { max: 10.0, typical: 6.0 },
        compressibility: 0.25,
        flowability: 0.55,
        carrIndex: 28,
        hausnerRatio: 1.39,
        hygroscopicity: 'Юқори',
        pH: { range: [5.5, 7.5], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.78,
        dissolutionEffect: 0.90,
        disintegrationEffect: 0.93,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 1, max: 5, unit: '%' },
        description: 'Суперпарчаловчи — шишиш механизми. Паст миқдорда юқори самара.'
    },

    'SODIUM_STARCH_GLYCOLATE': {
        id: 'SODIUM_STARCH_GLYCOLATE',
        name: 'Sodium Starch Glycolate',
        nameRu: 'Натрия крахмалгликолат',
        nameUz: 'Натрий крахмал гликолат',
        tradeName: 'Explotab / Primojel',
        casNumber: '9063-38-1',
        categories: ['SUPERDISINTEGRANT'],
        molecularWeight: null,
        empiricalFormula: 'Cross-linked CMC starch',
        solubility: { water: 'Шишийди (200-300% сув)', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.76, tapped: 0.98, true: 1.540 },
        particleSize: { mean: 45, range: [30, 100] },
        moistureContent: { max: 10.0, typical: 7.0 },
        compressibility: 0.30,
        flowability: 0.65,
        carrIndex: 22,
        hausnerRatio: 1.28,
        hygroscopicity: 'Юқори',
        pH: { range: [5.5, 7.5], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.75,
        dissolutionEffect: 0.85,
        disintegrationEffect: 0.90,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 8, unit: '%' },
        description: 'Яхши суперпарчаловчи, ўзининг массасидан 200-300% кўп сув ютади.'
    },

    // ==================== БОҒЛОВЧИЛАР ====================

    'PVP_K30': {
        id: 'PVP_K30',
        name: 'Povidone K-30 (PVP K-30)',
        nameRu: 'Повидон К-30 (ПВП К-30)',
        nameUz: 'Повидон К-30',
        tradeName: 'Plasdone K-29/32 / Kollidon 30',
        casNumber: '9003-39-8',
        categories: ['BINDER'],
        molecularWeight: 50000,
        empiricalFormula: '(C6H9NO)n',
        solubility: { water: 'Жуда яхши эрийди', ethanol: 'Эрийди' },
        solubilityValue: 1000,
        density: { bulk: 0.30, tapped: 0.45, true: 1.180 },
        particleSize: { mean: 60, range: [30, 120] },
        moistureContent: { max: 5.0, typical: 3.0 },
        compressibility: 0.40,
        flowability: 0.55,
        carrIndex: 28,
        hausnerRatio: 1.39,
        hygroscopicity: 'Юқори',
        pH: { range: [3.0, 7.0], typical: 4.5 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.72,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 5, unit: '%' },
        description: 'Сувда эрийдиган боғловчи. Ҳўл гранулляция учун мос. Юқори миқдорда парчаланишни секинлаштиради.'
    },

    'HPMC_E5': {
        id: 'HPMC_E5',
        name: 'Hypromellose (HPMC) E5',
        nameRu: 'Гипромеллоза (ГПМЦ) E5',
        nameUz: 'Гипромеллоза (ГПМЦ) E5',
        tradeName: 'Methocel E5 / Pharmacoat 606',
        casNumber: '9004-65-3',
        categories: ['BINDER', 'COATING'],
        molecularWeight: 26000,
        empiricalFormula: 'Methylcellulose derivative',
        solubility: { water: 'Эрийди (совуқ сувда)', ethanol: 'Қисман' },
        solubilityValue: 100,
        density: { bulk: 0.35, tapped: 0.52, true: 1.290 },
        particleSize: { mean: 80, range: [40, 160] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.50,
        flowability: 0.55,
        carrIndex: 28,
        hausnerRatio: 1.39,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.92,
        stabilityContribution: 0.88,
        dissolutionEffect: 0.70,
        disintegrationEffect: 0.45,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 6, unit: '%' },
        description: 'Боғловчи ва пленка ҳосил қилувчи агент. Қобиқ учун асосий модда. Барқарорлик юқори.'
    },

    // ==================== МОЙЛОВЧИЛАР ====================

    'MAGNESIUM_STEARATE': {
        id: 'MAGNESIUM_STEARATE',
        name: 'Magnesium Stearate',
        nameRu: 'Магния стеарат',
        nameUz: 'Магний стеарат',
        tradeName: 'HyQual / MagGran',
        casNumber: '557-04-0',
        categories: ['LUBRICANT'],
        molecularWeight: 591.27,
        empiricalFormula: 'C36H70MgO4',
        solubility: { water: 'Практик эримайди', ethanol: 'Қисман' },
        solubilityValue: 0.003,
        density: { bulk: 0.16, tapped: 0.25, true: 1.092 },
        particleSize: { mean: 10, range: [2, 30] },
        moistureContent: { max: 4.0, typical: 2.5 },
        compressibility: 0.15,
        flowability: 0.40,
        carrIndex: 35,
        hausnerRatio: 1.54,
        hygroscopicity: 'Паст',
        pH: { range: [7.0, 8.5], typical: 7.5 },
        compatibilityWithCiprofloxacin: 0.82,
        stabilityContribution: 0.80,
        dissolutionEffect: 0.35, // Юқори миқдорда эришни секинлаштиради!
        disintegrationEffect: 0.30, // Гидрофоб — парчаланишга салбий
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.25, max: 1.5, unit: '%' },
        description: 'Энг кенг қўлланиладиган мойловчи. ДИҚҚАТ: 1.5% дан ошса эришни ва парчаланишни секинлаштиради!'
    },

    'STEARIC_ACID': {
        id: 'STEARIC_ACID',
        name: 'Stearic Acid',
        nameRu: 'Стеариновая кислота',
        nameUz: 'Стеарин кислотаси',
        tradeName: 'Hystrene / Industrene',
        casNumber: '57-11-4',
        categories: ['LUBRICANT'],
        molecularWeight: 284.48,
        empiricalFormula: 'C18H36O2',
        solubility: { water: 'Практик эримайди', ethanol: 'Қисман (иссиқ)' },
        solubilityValue: 0.0003,
        density: { bulk: 0.45, tapped: 0.60, true: 0.941 },
        particleSize: { mean: 50, range: [20, 100] },
        moistureContent: { max: 0.5, typical: 0.2 },
        compressibility: 0.20,
        flowability: 0.50,
        carrIndex: 25,
        hausnerRatio: 1.33,
        hygroscopicity: 'Жуда паст',
        pH: { range: [2.0, 3.5], typical: 2.5 },
        compatibilityWithCiprofloxacin: 0.78,
        stabilityContribution: 0.75,
        dissolutionEffect: 0.40,
        disintegrationEffect: 0.35,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 2.0, unit: '%' },
        description: 'Мойловчи. Магний стеаратга ўхшаш, лекин бироз кучсизроқ мойловчи хусусият.'
    },

    'SODIUM_STEARYL_FUMARATE': {
        id: 'SODIUM_STEARYL_FUMARATE',
        name: 'Sodium Stearyl Fumarate',
        nameRu: 'Натрия стеарилфумарат',
        nameUz: 'Натрий стеарил фумарат',
        tradeName: 'Pruv',
        casNumber: '4070-80-8',
        categories: ['LUBRICANT'],
        molecularWeight: 390.52,
        empiricalFormula: 'C22H39NaO4',
        solubility: { water: 'Жуда кам', ethanol: 'Жуда кам' },
        solubilityValue: 0.01,
        density: { bulk: 0.20, tapped: 0.35, true: 1.1 },
        particleSize: { mean: 15, range: [5, 40] },
        moistureContent: { max: 5.0, typical: 2.0 },
        compressibility: 0.20,
        flowability: 0.45,
        carrIndex: 30,
        hausnerRatio: 1.43,
        hygroscopicity: 'Паст',
        pH: { range: [8.0, 10.0], typical: 9.0 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.85,
        dissolutionEffect: 0.60,
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 2.0, unit: '%' },
        description: 'Замонавий мойловчи — магний стеаратга нисбатан эришга камроқ салбий таъсир кўрсатади.'
    },

    // ==================== СИРҒАНУВЧИЛАР ====================

    'COLLOIDAL_SIO2': {
        id: 'COLLOIDAL_SIO2',
        name: 'Colloidal Silicon Dioxide',
        nameRu: 'Кремния диоксид коллоидный',
        nameUz: 'Коллоид кремний диоксид',
        tradeName: 'Aerosil 200 / Cab-O-Sil',
        casNumber: '7631-86-9',
        categories: ['GLIDANT'],
        molecularWeight: 60.08,
        empiricalFormula: 'SiO2',
        solubility: { water: 'Практик эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.04, tapped: 0.06, true: 2.200 },
        particleSize: { mean: 0.012, range: [0.007, 0.040] },
        moistureContent: { max: 2.5, typical: 1.0 },
        compressibility: 0.10,
        flowability: 0.30,
        carrIndex: 40,
        hausnerRatio: 1.67,
        hygroscopicity: 'Ўрта',
        pH: { range: [3.5, 5.5], typical: 4.0 },
        compatibilityWithCiprofloxacin: 0.95,
        stabilityContribution: 0.88,
        dissolutionEffect: 0.50,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.1, max: 1.0, unit: '%' },
        description: 'Ажойиб сирғанувчи. Кукунлар оқувчанлигини кескин яхшилайди. 0.1-1% етарли.'
    },

    'TALC': {
        id: 'TALC',
        name: 'Talc',
        nameRu: 'Тальк',
        nameUz: 'Тальк',
        tradeName: 'Pharma Talc',
        casNumber: '14807-96-6',
        categories: ['GLIDANT', 'LUBRICANT'],
        molecularWeight: 379.27,
        empiricalFormula: 'Mg3Si4O10(OH)2',
        solubility: { water: 'Практик эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.40, tapped: 0.60, true: 2.750 },
        particleSize: { mean: 10, range: [2, 40] },
        moistureContent: { max: 0.5, typical: 0.2 },
        compressibility: 0.15,
        flowability: 0.60,
        carrIndex: 25,
        hausnerRatio: 1.33,
        hygroscopicity: 'Жуда паст',
        pH: { range: [7.0, 9.5], typical: 8.5 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.85,
        dissolutionEffect: 0.45,
        disintegrationEffect: 0.45,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 1, max: 5, unit: '%' },
        description: 'Сирғанувчи ва мойловчи. Қобиқ таркибида ёпишмага қарши ишлатилади.'
    },

    // ==================== ҚОБИҚ МОДДАЛАРИ ====================

    'HPMC_COATING': {
        id: 'HPMC_COATING',
        name: 'Hypromellose (HPMC) for Coating',
        nameRu: 'Гипромеллоза для покрытия',
        nameUz: 'Гипромеллоза (қобиқ учун)',
        tradeName: 'Opadry / Pharmacoat',
        casNumber: '9004-65-3',
        categories: ['COATING'],
        molecularWeight: 86000,
        empiricalFormula: 'Methylcellulose derivative',
        solubility: { water: 'Эрийди', ethanol: 'Қисман' },
        solubilityValue: 100,
        density: { bulk: 0.35, tapped: 0.52, true: 1.290 },
        particleSize: { mean: 80, range: [40, 160] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.50,
        flowability: 0.55,
        carrIndex: 28,
        hausnerRatio: 1.39,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.95,
        stabilityContribution: 0.92,
        dissolutionEffect: 0.80,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 6, unit: '%' },
        description: 'Энг кенг қўлланиладиган пленка қобиқ агенти. Шаффоф, силлиқ ва мустаҳкам қобиқ ҳосил қилади.'
    },

    'PVA': {
        id: 'PVA',
        name: 'Polyvinyl Alcohol (PVA)',
        nameRu: 'Поливиниловый спирт',
        nameUz: 'Поливинил спирт (ПВС)',
        tradeName: 'Opadry II / Kollicoat IR',
        casNumber: '9002-89-5',
        categories: ['COATING'],
        molecularWeight: 31000,
        empiricalFormula: '(C2H4O)n',
        solubility: { water: 'Яхши эрийди', ethanol: 'Кам' },
        solubilityValue: 200,
        density: { bulk: 0.40, tapped: 0.55, true: 1.260 },
        particleSize: { mean: 100, range: [50, 200] },
        moistureContent: { max: 5.0, typical: 3.0 },
        compressibility: 0.45,
        flowability: 0.60,
        carrIndex: 22,
        hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [4.0, 6.5], typical: 5.0 },
        compatibilityWithCiprofloxacin: 0.93,
        stabilityContribution: 0.90,
        dissolutionEffect: 0.82,
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 5, unit: '%' },
        description: 'Замонавий қобиқ агенти (Opadry II таркибида). Тез эрийди, силлиқ юза беради.'
    },

    // ==================== ПЛАСТИФИКАТОРЛАР ====================

    'PEG_400': {
        id: 'PEG_400',
        name: 'Polyethylene Glycol 400 (PEG 400)',
        nameRu: 'ПЭГ 400 (Макрогол 400)',
        nameUz: 'ПЭГ 400 (Макрогол 400)',
        tradeName: 'Carbowax 400',
        casNumber: '25322-68-3',
        categories: ['PLASTICIZER'],
        molecularWeight: 400,
        empiricalFormula: 'H(OCH2CH2)nOH',
        solubility: { water: 'Тўлиқ эрийди', ethanol: 'Тўлиқ эрийди' },
        solubilityValue: 10000,
        density: { bulk: null, tapped: null, true: 1.128 },
        particleSize: null, // Liquid
        moistureContent: { max: 1.0, typical: 0.3 },
        compressibility: null,
        flowability: null,
        carrIndex: null,
        hausnerRatio: null,
        hygroscopicity: 'Юқори',
        pH: { range: [4.5, 7.5], typical: 6.0 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.82,
        dissolutionEffect: 0.80,
        disintegrationEffect: 0.60,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 3, unit: '%' },
        description: 'Суюқ пластификатор. Қобиқларга мослашувчанлик беради. Сирт-фаол модда сифатида ҳам.'
    },

    'PEG_6000': {
        id: 'PEG_6000',
        name: 'Polyethylene Glycol 6000 (PEG 6000)',
        nameRu: 'ПЭГ 6000 (Макрогол 6000)',
        nameUz: 'ПЭГ 6000 (Макрогол 6000)',
        tradeName: 'Carbowax 6000',
        casNumber: '25322-68-3',
        categories: ['PLASTICIZER'],
        molecularWeight: 6000,
        empiricalFormula: 'H(OCH2CH2)nOH',
        solubility: { water: 'Яхши эрийди', ethanol: 'Яхши эрийди' },
        solubilityValue: 700,
        density: { bulk: 0.55, tapped: 0.72, true: 1.212 },
        particleSize: { mean: 200, range: [100, 400] },
        moistureContent: { max: 1.0, typical: 0.3 },
        compressibility: 0.35,
        flowability: 0.70,
        carrIndex: 20,
        hausnerRatio: 1.25,
        hygroscopicity: 'Ўрта',
        pH: { range: [4.5, 7.5], typical: 6.0 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.80,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 3, unit: '%' },
        description: 'Қаттиқ пластификатор. Қобиқларда ва матрица таблеткаларда.'
    },

    'TRIACETIN': {
        id: 'TRIACETIN',
        name: 'Triacetin (Glyceryl Triacetate)',
        nameRu: 'Триацетин',
        nameUz: 'Триацетин',
        tradeName: 'Triacetin',
        casNumber: '102-76-1',
        categories: ['PLASTICIZER'],
        molecularWeight: 218.21,
        empiricalFormula: 'C9H14O6',
        solubility: { water: '72 мг/мл', ethanol: 'Тўлиқ' },
        solubilityValue: 72,
        density: { bulk: null, tapped: null, true: 1.155 },
        particleSize: null,
        moistureContent: { max: 0.5, typical: 0.1 },
        compressibility: null,
        flowability: null,
        carrIndex: null,
        hausnerRatio: null,
        hygroscopicity: 'Паст',
        pH: { range: [5.0, 7.0], typical: 6.0 },
        compatibilityWithCiprofloxacin: 0.92,
        stabilityContribution: 0.88,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.60,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.1, max: 1.5, unit: '%' },
        description: 'Сифатли пластификатор. ГПМЦ қобиқларига мослашувчанлик ва силлиқлик беради.'
    },

    // ==================== МАТЛАШТИРУВЧИЛАР ====================

    'TITANIUM_DIOXIDE': {
        id: 'TITANIUM_DIOXIDE',
        name: 'Titanium Dioxide',
        nameRu: 'Титана диоксид',
        nameUz: 'Титан диоксид',
        tradeName: 'E171',
        casNumber: '13463-67-7',
        categories: ['OPACIFIER', 'COLORANT'],
        molecularWeight: 79.87,
        empiricalFormula: 'TiO2',
        solubility: { water: 'Эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.50, tapped: 0.80, true: 4.230 },
        particleSize: { mean: 0.3, range: [0.1, 1.0] },
        moistureContent: { max: 0.5, typical: 0.2 },
        compressibility: 0.20,
        flowability: 0.50,
        carrIndex: 28,
        hausnerRatio: 1.39,
        hygroscopicity: 'Жуда паст',
        pH: { range: [3.5, 9.0], typical: 7.0 },
        compatibilityWithCiprofloxacin: 0.95,
        stabilityContribution: 0.90,
        dissolutionEffect: 0.50,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 3, unit: '%' },
        description: 'Оқ ранг ва матлаштириш учун. Ёруғликдан ҳимоя қилади — барқарорликни оширади.'
    },

    // ==================== ПОЛИДЕКСТРОЗА ====================

    'POLYDEXTROSE': {
        id: 'POLYDEXTROSE',
        name: 'Polydextrose',
        nameRu: 'Полидекстроза',
        nameUz: 'Полидекстроза',
        tradeName: 'Litesse',
        casNumber: '68424-04-4',
        categories: ['FILLER', 'COATING'],
        molecularWeight: null,
        empiricalFormula: 'Polymer of D-glucose',
        solubility: { water: 'Яхши эрийди', ethanol: 'Қисман' },
        solubilityValue: 800,
        density: { bulk: 0.50, tapped: 0.65, true: 1.350 },
        particleSize: { mean: 200, range: [50, 500] },
        moistureContent: { max: 4.0, typical: 2.0 },
        compressibility: 0.45,
        flowability: 0.65,
        carrIndex: 22,
        hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [2.5, 5.5], typical: 3.5 },
        compatibilityWithCiprofloxacin: 0.85,
        stabilityContribution: 0.80,
        dissolutionEffect: 0.70,
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 1, max: 5, unit: '%' },
        description: 'Қобиқ таркибида тўлдирувчи сифатида ва пленка мустаҳкамлигини оширади.'
    },

    // ==================== НАТРИЙ ЦИТРАТ ====================

    'SODIUM_CITRATE': {
        id: 'SODIUM_CITRATE',
        name: 'Sodium Citrate Dihydrate',
        nameRu: 'Натрия цитрат дигидрат',
        nameUz: 'Натрий цитрат дигидрат',
        tradeName: 'E331',
        casNumber: '6132-04-3',
        categories: ['FILLER'],
        molecularWeight: 294.10,
        empiricalFormula: 'C6H5Na3O7·2H2O',
        solubility: { water: '425 мг/мл', ethanol: 'Эримайди' },
        solubilityValue: 425,
        density: { bulk: 0.60, tapped: 0.80, true: 1.790 },
        particleSize: { mean: 200, range: [100, 400] },
        moistureContent: { max: 13.0, typical: 11.5 },
        compressibility: 0.40,
        flowability: 0.70,
        carrIndex: 22,
        hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [7.0, 8.5], typical: 8.0 },
        compatibilityWithCiprofloxacin: 0.80,
        stabilityContribution: 0.72,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.60,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 1, max: 5, unit: '%' },
        description: 'Буфер агент ва тўлдирувчи. pH ни созлашда ёрдам беради.'
    },

    // ==================== ҚЎШИМЧА МОДДАЛАР (Фойдаланувчи рўйхатидан) ====================

    'SODIUM_LAURYL_SULFATE': {
        id: 'SODIUM_LAURYL_SULFATE',
        name: 'Sodium Lauryl Sulfate (SLS)',
        nameRu: 'Натрия лаурилсульфат',
        nameUz: 'Натрий лаурилсульфат',
        tradeName: 'SLS / SDS',
        casNumber: '151-21-3',
        categories: ['SURFACTANT'],
        molecularWeight: 288.38,
        empiricalFormula: 'C12H25NaO4S',
        solubility: { water: 'Яхши эрийди (150 мг/мл)', ethanol: 'Қисман' },
        solubilityValue: 150,
        density: { bulk: 0.35, tapped: 0.50, true: 1.050 },
        particleSize: { mean: 100, range: [40, 300] },
        moistureContent: { max: 5.0, typical: 2.0 },
        compressibility: 0.30, flowability: 0.55, carrIndex: 25, hausnerRatio: 1.33,
        hygroscopicity: 'Ўрта',
        pH: { range: [7.0, 9.5], typical: 8.5 },
        compatibilityWithCiprofloxacin: 0.82,
        stabilityContribution: 0.70,
        dissolutionEffect: 0.92, // Эришни жуда кўп тезлаштиради
        disintegrationEffect: 0.70,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 2.0, unit: '%' },
        description: 'Анион сирт-фаол модда. Эришни кескин тезлаштиради (wetting agent). BCS IV дорилар учун муҳим.'
    },

    'CITRIC_ACID': {
        id: 'CITRIC_ACID',
        name: 'Citric Acid (Anhydrous)',
        nameRu: 'Лимонная кислота (безводная)',
        nameUz: 'Лимон кислотаси',
        tradeName: 'E330',
        casNumber: '77-92-9',
        categories: ['FILLER'],
        molecularWeight: 192.12,
        empiricalFormula: 'C6H8O7',
        solubility: { water: '592 мг/мл', ethanol: '383 мг/мл' },
        solubilityValue: 592,
        density: { bulk: 0.70, tapped: 0.85, true: 1.665 },
        particleSize: { mean: 200, range: [50, 500] },
        moistureContent: { max: 0.5, typical: 0.1 },
        compressibility: 0.40, flowability: 0.70, carrIndex: 18, hausnerRatio: 1.22,
        hygroscopicity: 'Ўрта',
        pH: { range: [1.5, 3.0], typical: 2.2 },
        compatibilityWithCiprofloxacin: 0.85,
        stabilityContribution: 0.65,
        dissolutionEffect: 0.82, // pH микромуҳитини пасайтириш орқали
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 3, unit: '%' },
        description: 'pH созловчи ва буфер агент. Ципрофлоксацин эришлигини pH пасайтириш орқали яхшилайди.'
    },

    'CALCIUM_CARBONATE': {
        id: 'CALCIUM_CARBONATE',
        name: 'Calcium Carbonate',
        nameRu: 'Кальция карбонат',
        nameUz: 'Кальций карбонат',
        tradeName: 'E170',
        casNumber: '471-34-1',
        categories: ['FILLER', 'OPACIFIER'],
        molecularWeight: 100.09,
        empiricalFormula: 'CaCO3',
        solubility: { water: 'Практик эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0.013,
        density: { bulk: 0.80, tapped: 1.10, true: 2.710 },
        particleSize: { mean: 5, range: [1, 20] },
        moistureContent: { max: 1.0, typical: 0.3 },
        compressibility: 0.45, flowability: 0.80, carrIndex: 15, hausnerRatio: 1.18,
        hygroscopicity: 'Жуда паст',
        pH: { range: [8.5, 9.5], typical: 9.0 },
        compatibilityWithCiprofloxacin: 0.60, // Кальций хелат ҳосил қилиши мумкин!
        stabilityContribution: 0.78,
        dissolutionEffect: 0.40,
        disintegrationEffect: 0.45,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 1, max: 10, unit: '%' },
        description: 'Тўлдирувчи. ДИҚҚАТ: Кальций ципрофлоксацин билан хелат комплекс ҳосил қилиб биомавжудликни пасайтириши мумкин!'
    },

    'METHYLPARABEN': {
        id: 'METHYLPARABEN',
        name: 'Methylparaben (Methyl 4-hydroxybenzoate)',
        nameRu: 'Метилпарабен (метилпарагидроксибензоат)',
        nameUz: 'Метилпарабен',
        tradeName: 'Nipagin M / E218',
        casNumber: '99-76-3',
        categories: ['ANTIOXIDANT'],
        molecularWeight: 152.15,
        empiricalFormula: 'C8H8O3',
        solubility: { water: '2.5 мг/мл', ethanol: 'Яхши' },
        solubilityValue: 2.5,
        density: { bulk: 0.45, tapped: 0.60, true: 1.352 },
        particleSize: { mean: 100, range: [30, 300] },
        moistureContent: { max: 0.5, typical: 0.1 },
        compressibility: 0.30, flowability: 0.55, carrIndex: 25, hausnerRatio: 1.33,
        hygroscopicity: 'Паст',
        pH: { range: [3.0, 6.0], typical: 4.5 },
        compatibilityWithCiprofloxacin: 0.85,
        stabilityContribution: 0.82,
        dissolutionEffect: 0.50,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.02, max: 0.3, unit: '%' },
        description: 'Консервант ва антиоксидант. Қобиқ суспензиясида микробиологик тозалик учун.'
    },

    'PROPYLPARABEN': {
        id: 'PROPYLPARABEN',
        name: 'Propylparaben (Propyl 4-hydroxybenzoate)',
        nameRu: 'Пропилпарабен (пропилпарагидроксибензоат)',
        nameUz: 'Пропилпарабен',
        tradeName: 'Nipasol / E216',
        casNumber: '94-13-3',
        categories: ['ANTIOXIDANT'],
        molecularWeight: 180.20,
        empiricalFormula: 'C10H12O3',
        solubility: { water: '0.5 мг/мл', ethanol: 'Яхши' },
        solubilityValue: 0.5,
        density: { bulk: 0.45, tapped: 0.60, true: 1.288 },
        particleSize: { mean: 100, range: [30, 300] },
        moistureContent: { max: 0.5, typical: 0.1 },
        compressibility: 0.30, flowability: 0.55, carrIndex: 25, hausnerRatio: 1.33,
        hygroscopicity: 'Паст',
        pH: { range: [3.0, 6.0], typical: 4.5 },
        compatibilityWithCiprofloxacin: 0.85,
        stabilityContribution: 0.82,
        dissolutionEffect: 0.50,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.01, max: 0.2, unit: '%' },
        description: 'Консервант. Метилпарабен билан биргаликда синергетик самара.'
    },

    'CALCIUM_PHOSPHATE_ANHYDROUS': {
        id: 'CALCIUM_PHOSPHATE_ANHYDROUS',
        name: 'Dibasic Calcium Phosphate Anhydrous',
        nameRu: 'Кальций фосфат двузамещенный безводный',
        nameUz: 'Кальций фосфат (сувсиз)',
        tradeName: 'Fujicalin / A-TAB',
        casNumber: '7757-93-9',
        categories: ['FILLER'],
        molecularWeight: 136.06,
        empiricalFormula: 'CaHPO4',
        solubility: { water: 'Практик эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0.02,
        density: { bulk: 0.75, tapped: 1.00, true: 2.890 },
        particleSize: { mean: 120, range: [40, 250] },
        moistureContent: { max: 0.5, typical: 0.1 },
        compressibility: 0.60, flowability: 0.85, carrIndex: 13, hausnerRatio: 1.15,
        hygroscopicity: 'Жуда паст',
        pH: { range: [6.5, 7.5], typical: 7.0 },
        compatibilityWithCiprofloxacin: 0.65,
        stabilityContribution: 0.85,
        dissolutionEffect: 0.40,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 5, max: 40, unit: '%' },
        description: 'Ноорганик тўлдирувчи. Жуда яхши оқувчанлик. Кальций хелат хавфи мавжуд.'
    },

    'IRON_OXIDE_YELLOW': {
        id: 'IRON_OXIDE_YELLOW',
        name: 'Iron Oxide Yellow',
        nameRu: 'Оксид железа желтый',
        nameUz: 'Темир оксид (сариқ)',
        tradeName: 'E172 (Yellow)',
        casNumber: '51274-00-1',
        categories: ['COLORANT'],
        molecularWeight: 159.69,
        empiricalFormula: 'FeOOH',
        solubility: { water: 'Эримайди', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.60, tapped: 0.90, true: 4.000 },
        particleSize: { mean: 0.5, range: [0.1, 2.0] },
        moistureContent: { max: 1.0, typical: 0.3 },
        compressibility: 0.20, flowability: 0.50, carrIndex: 28, hausnerRatio: 1.39,
        hygroscopicity: 'Жуда паст',
        pH: { range: [3.0, 9.0], typical: 7.0 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.88,
        dissolutionEffect: 0.50,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.1, max: 1.5, unit: '%' },
        description: 'Қобиқ рангловчиси. Ёруғликдан ҳимоя қилади. Барқарорликни оширади.'
    },

    'OPADRY_WHITE': {
        id: 'OPADRY_WHITE',
        name: 'Opadry White (HPMC-based premix)',
        nameRu: 'Opadry White (на основе ГПМЦ)',
        nameUz: 'Opadry White (ГПМЦ асосидаги аралашма)',
        tradeName: 'Opadry White',
        casNumber: 'Premix',
        categories: ['COATING'],
        molecularWeight: null,
        empiricalFormula: 'HPMC + PEG + TiO2 + Talc',
        solubility: { water: 'Эрийди (суспензия)', ethanol: 'Қисман' },
        solubilityValue: 100,
        density: { bulk: 0.45, tapped: 0.60, true: 1.350 },
        particleSize: { mean: 60, range: [20, 150] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.40, flowability: 0.60, carrIndex: 22, hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.93,
        stabilityContribution: 0.92,
        dissolutionEffect: 0.78,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 6, unit: '%' },
        description: 'Тайёр ГПМЦ-асосидаги қобиқ аралашмаси. Ишлатиш осон, натижа барқарор.'
    },

    'OPADRY_II_WHITE': {
        id: 'OPADRY_II_WHITE',
        name: 'Opadry II White (PVA-based premix)',
        nameRu: 'OPADRY II белый (на основе ПВС)',
        nameUz: 'Opadry II White (ПВС асосидаги аралашма)',
        tradeName: 'Opadry II White',
        casNumber: 'Premix',
        categories: ['COATING'],
        molecularWeight: null,
        empiricalFormula: 'PVA + PEG + TiO2 + Talc',
        solubility: { water: 'Эрийди (суспензия)', ethanol: 'Қисман' },
        solubilityValue: 150,
        density: { bulk: 0.45, tapped: 0.60, true: 1.320 },
        particleSize: { mean: 60, range: [20, 150] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.40, flowability: 0.60, carrIndex: 22, hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [4.0, 7.0], typical: 5.5 },
        compatibilityWithCiprofloxacin: 0.95,
        stabilityContribution: 0.93,
        dissolutionEffect: 0.85,
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 5, unit: '%' },
        description: 'Замонавий ПВС-асосидаги қобиқ. Opadry I дан тез эрийди, силлиқ юза, намликдан яхши ҳимоя.'
    },

    'ETHYLCELLULOSE': {
        id: 'ETHYLCELLULOSE',
        name: 'Ethylcellulose',
        nameRu: 'Этилцеллюлоза',
        nameUz: 'Этилцеллюлоза',
        tradeName: 'Ethocel / Aqualon EC',
        casNumber: '9004-57-3',
        categories: ['COATING'],
        molecularWeight: null,
        empiricalFormula: 'Ethyl ether of cellulose',
        solubility: { water: 'Эримайди', ethanol: 'Эрийди' },
        solubilityValue: 0,
        density: { bulk: 0.35, tapped: 0.50, true: 1.120 },
        particleSize: { mean: 80, range: [30, 200] },
        moistureContent: { max: 3.0, typical: 1.5 },
        compressibility: 0.40, flowability: 0.55, carrIndex: 25, hausnerRatio: 1.33,
        hygroscopicity: 'Паст',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.90,
        dissolutionEffect: 0.35, // Эришни секинлаштиради (sustained-release)
        disintegrationEffect: 0.25,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 1, max: 5, unit: '%' },
        description: 'Сувда эримайдиган қобиқ агенти. Sustained-release учун. Тез чиқиш талаб қилинса мос эмас!'
    },

    'PROPYLENE_GLYCOL': {
        id: 'PROPYLENE_GLYCOL',
        name: 'Propylene Glycol',
        nameRu: 'Пропиленгликоль',
        nameUz: 'Пропиленгликол',
        tradeName: 'E1520',
        casNumber: '57-55-6',
        categories: ['PLASTICIZER'],
        molecularWeight: 76.09,
        empiricalFormula: 'C3H8O2',
        solubility: { water: 'Тўлиқ аралашади', ethanol: 'Тўлиқ' },
        solubilityValue: 10000,
        density: { bulk: null, tapped: null, true: 1.036 },
        particleSize: null,
        moistureContent: { max: 0.5, typical: 0.1 },
        compressibility: null, flowability: null, carrIndex: null, hausnerRatio: null,
        hygroscopicity: 'Юқори',
        pH: { range: [5.0, 8.0], typical: 7.0 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.78,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.55,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 3, unit: '%' },
        description: 'Суюқ пластификатор ва ко-эритувчи. Қобиқ суспензиясида ишлатилади.'
    },

    'PEG_3350': {
        id: 'PEG_3350',
        name: 'Polyethylene Glycol 3350 (Macrogol 3350)',
        nameRu: 'ПЭГ 3350 (Макрогол 3350)',
        nameUz: 'ПЭГ 3350 (Макрогол 3350)',
        tradeName: 'Carbowax 3350',
        casNumber: '25322-68-3',
        categories: ['PLASTICIZER'],
        molecularWeight: 3350,
        empiricalFormula: 'H(OCH2CH2)nOH',
        solubility: { water: 'Яхши эрийди', ethanol: 'Яхши' },
        solubilityValue: 800,
        density: { bulk: 0.52, tapped: 0.68, true: 1.200 },
        particleSize: { mean: 180, range: [80, 350] },
        moistureContent: { max: 1.0, typical: 0.3 },
        compressibility: 0.38, flowability: 0.72, carrIndex: 18, hausnerRatio: 1.22,
        hygroscopicity: 'Ўрта',
        pH: { range: [4.5, 7.5], typical: 6.0 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.82,
        dissolutionEffect: 0.78,
        disintegrationEffect: 0.58,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 3, unit: '%' },
        description: 'Пластификатор ва мойловчи. Қобиқ таркибида юзага силлиқлик беради.'
    },

    'PEG_4000': {
        id: 'PEG_4000',
        name: 'Polyethylene Glycol 4000 (Macrogol 4000)',
        nameRu: 'ПЭГ 4000 (Макрогол 4000)',
        nameUz: 'ПЭГ 4000 (Макрогол 4000)',
        tradeName: 'Carbowax 4000',
        casNumber: '25322-68-3',
        categories: ['PLASTICIZER'],
        molecularWeight: 4000,
        empiricalFormula: 'H(OCH2CH2)nOH',
        solubility: { water: 'Яхши эрийди', ethanol: 'Яхши' },
        solubilityValue: 750,
        density: { bulk: 0.53, tapped: 0.70, true: 1.205 },
        particleSize: { mean: 190, range: [90, 380] },
        moistureContent: { max: 1.0, typical: 0.3 },
        compressibility: 0.36, flowability: 0.71, carrIndex: 19, hausnerRatio: 1.23,
        hygroscopicity: 'Ўрта',
        pH: { range: [4.5, 7.5], typical: 6.0 },
        compatibilityWithCiprofloxacin: 0.89,
        stabilityContribution: 0.81,
        dissolutionEffect: 0.76,
        disintegrationEffect: 0.56,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.5, max: 3, unit: '%' },
        description: 'Пластификатор. ГПМЦ қобиқларда кенг ишлатилади.'
    },

    'LECITHIN_SOY': {
        id: 'LECITHIN_SOY',
        name: 'Lecithin (Soy)',
        nameRu: 'Лецитин (соевый)',
        nameUz: 'Лецитин (соя)',
        tradeName: 'E322',
        casNumber: '8002-43-5',
        categories: ['SURFACTANT'],
        molecularWeight: 750,
        empiricalFormula: 'Phospholipid mixture',
        solubility: { water: 'Диспергирланади', ethanol: 'Эрийди' },
        solubilityValue: 0,
        density: { bulk: null, tapped: null, true: 1.050 },
        particleSize: null,
        moistureContent: { max: 2.0, typical: 0.5 },
        compressibility: null, flowability: null, carrIndex: null, hausnerRatio: null,
        hygroscopicity: 'Паст',
        pH: { range: [3.0, 6.0], typical: 4.0 },
        compatibilityWithCiprofloxacin: 0.85,
        stabilityContribution: 0.78,
        dissolutionEffect: 0.80,
        disintegrationEffect: 0.60,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 0.1, max: 2.0, unit: '%' },
        description: 'Табиий эмульгатор ва сирт-фаол модда. Қобиқ суспензиясида ёпишмага қарши.'
    },

    'K_COAT_RFC': {
        id: 'K_COAT_RFC',
        name: 'K-Coat RFC (Ready-to-use Film Coating)',
        nameRu: 'K-Coat RFC (готовое покрытие)',
        nameUz: 'K-Coat RFC (тайёр қобиқ аралашмаси)',
        tradeName: 'K-Coat RFC',
        casNumber: 'Premix',
        categories: ['COATING'],
        molecularWeight: null,
        empiricalFormula: 'HPMC + Plasticizer + Opacifier',
        solubility: { water: 'Эрийди (суспензия)', ethanol: 'Қисман' },
        solubilityValue: 100,
        density: { bulk: 0.45, tapped: 0.60, true: 1.300 },
        particleSize: { mean: 60, range: [20, 150] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.40, flowability: 0.60, carrIndex: 22, hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.88,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.48,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 6, unit: '%' },
        description: 'Тайёр қобиқ аралашмаси. Ишлатиш осон, стандарт натижа.'
    },

    'TABCOAT_TC': {
        id: 'TABCOAT_TC',
        name: 'Tabcoat-TC',
        nameRu: 'Tabcoat-TC',
        nameUz: 'Tabcoat-TC',
        tradeName: 'Tabcoat-TC',
        casNumber: 'Premix',
        categories: ['COATING'],
        molecularWeight: null,
        empiricalFormula: 'Premix film coating system',
        solubility: { water: 'Эрийди (суспензия)', ethanol: 'Қисман' },
        solubilityValue: 100,
        density: { bulk: 0.45, tapped: 0.60, true: 1.300 },
        particleSize: { mean: 60, range: [20, 150] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.40, flowability: 0.60, carrIndex: 22, hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.85,
        dissolutionEffect: 0.72,
        disintegrationEffect: 0.48,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 6, unit: '%' },
        description: 'Тайёр қобиқ тизими. Стандартлаштирилган натижа учун.'
    },

    'POTATO_STARCH': {
        id: 'POTATO_STARCH',
        name: 'Potato Starch',
        nameRu: 'Крахмал картофельный',
        nameUz: 'Картошка крахмали',
        tradeName: 'Starch (Potato)',
        casNumber: '9005-25-8',
        categories: ['FILLER', 'DISINTEGRANT', 'BINDER'],
        molecularWeight: null,
        empiricalFormula: '(C6H10O5)n',
        solubility: { water: 'Практик эримайди (совуқ)', ethanol: 'Эримайди' },
        solubilityValue: 0,
        density: { bulk: 0.50, tapped: 0.70, true: 1.500 },
        particleSize: { mean: 40, range: [15, 100] },
        moistureContent: { max: 18.0, typical: 14.0 },
        compressibility: 0.40, flowability: 0.45, carrIndex: 32, hausnerRatio: 1.47,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 7.5], typical: 6.0 },
        compatibilityWithCiprofloxacin: 0.88,
        stabilityContribution: 0.72,
        dissolutionEffect: 0.58,
        disintegrationEffect: 0.68,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 3, max: 15, unit: '%' },
        description: 'Парчаловчи ва тўлдирувчи. Маккажўхори крахмалига ўхшаш, лекин заррачалар каттароқ.'
    },

    'UNIVERSAL_GREEN_3124': {
        id: 'UNIVERSAL_GREEN_3124',
        name: 'Universal Green WT-3124',
        nameRu: 'Universal Green WT-3124',
        nameUz: 'Universal Green WT-3124',
        tradeName: 'WT-3124',
        casNumber: 'Premix',
        categories: ['COATING', 'COLORANT'],
        molecularWeight: null,
        empiricalFormula: 'HPMC + Green pigment premix',
        solubility: { water: 'Эрийди (суспензия)', ethanol: 'Қисман' },
        solubilityValue: 100,
        density: { bulk: 0.45, tapped: 0.60, true: 1.350 },
        particleSize: { mean: 60, range: [20, 150] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.40, flowability: 0.60, carrIndex: 22, hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.88,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 5, unit: '%' },
        description: 'Яшил рангли тайёр қобиқ аралашмаси. ГПМЦ асосида.'
    },

    'UNIVERSAL_GREEN_3128': {
        id: 'UNIVERSAL_GREEN_3128',
        name: 'Universal Green WT-3128',
        nameRu: 'Universal Green WT-3128',
        nameUz: 'Universal Green WT-3128',
        tradeName: 'WT-3128',
        casNumber: 'Premix',
        categories: ['COATING', 'COLORANT'],
        molecularWeight: null,
        empiricalFormula: 'HPMC + Green pigment premix',
        solubility: { water: 'Эрийди (суспензия)', ethanol: 'Қисман' },
        solubilityValue: 100,
        density: { bulk: 0.45, tapped: 0.60, true: 1.350 },
        particleSize: { mean: 60, range: [20, 150] },
        moistureContent: { max: 5.0, typical: 2.5 },
        compressibility: 0.40, flowability: 0.60, carrIndex: 22, hausnerRatio: 1.28,
        hygroscopicity: 'Ўрта',
        pH: { range: [5.0, 8.0], typical: 6.5 },
        compatibilityWithCiprofloxacin: 0.90,
        stabilityContribution: 0.88,
        dissolutionEffect: 0.75,
        disintegrationEffect: 0.50,
        safetyProfile: { gras: true, fdaApproved: true, ldCategory: 'Паст токсик' },
        optimalRange: { min: 2, max: 5, unit: '%' },
        description: 'Яшил рангли тайёр қобиқ аралашмаси. WT-3124 нинг модификацияси.'
    }
};

/**
 * Ципрофлоксацин (фаол модда) физик-кимёвий хоссалари
 */
const CIPROFLOXACIN_API = {
    name: 'Ciprofloxacin Hydrochloride',
    nameRu: 'Ципрофлоксацина гидрохлорид',
    nameUz: 'Ципрофлоксацин гидрохлорид',
    casNumber: '86393-32-0',
    molecularWeight: 385.82,
    empiricalFormula: 'C17H18FN3O3·HCl·H2O',
    bcsClass: 'IV (паст эришлик, паст ўтказувчанлик) / III (pH < 6)',
    pKa: [6.09, 8.74],
    solubility: {
        water_pH1: 30, // мг/мл (pH 1)
        water_pH4: 15,
        water_pH7: 1.4,
        water_pH9: 0.5,
        description: 'pH-боғлиқ эришлик. Кислотали муҳитда яхши, ишқорийда ёмон эрийди.'
    },
    meltingPoint: { range: [255, 257], unit: '°C' },
    logP: 0.28,
    doses: [250, 500, 750],
    halfLife: '4 соат',
    bioavailability: '70-80%',
    absorptionSite: 'Проксимал ингичка ичак',
    stability: {
        light: 'Ёруғликка сезгир (фотодеградация)',
        heat: '40°C/75% RH да 6 ойгача барқарор',
        humidity: 'Намликка ўрта сезувчанлик',
        pH_stability: 'pH 3-5 оралиғида энг барқарор'
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EXCIPIENT_CATEGORIES, EXCIPIENTS_DB, CIPROFLOXACIN_API };
}
